### PR TITLE
Add npm ignore

### PR DESCRIPTION
**Pull request by jdneo**

### CODE REVIEW

**Comment by poppinlp** [comment]
Maybe we could use `files` field which is an array of pattern in `package.json` to specify the files which we wanna include.
It's a white list mode which may reduce some unexpected ignores.

**Comment by jdneo** [comment]
@poppinlp Good to know that. Would you mind to make a PR for that?

**Comment by poppinlp** [comment]
OK. I'll do it tonight.
Seems I'm always looking the past things since I'm still in the interview process. T_T

**Comment by poppinlp** [comment]
And I owe a new leetcode module design. I still remember that. But I'm not pretty sure my time recently. 😢

**Pull request merged**
