### PR TITLE
Fix: LinkedIn login problem.

### PR DESCRIPTION
**Pull request by yihong0618**

### CODE REVIEW

**Comment by yihong0618** [comment]
@jdneo
I think we can hold this pr for https://github.com/LeetCode-OpenSource/vscode-leetcode/issues/563
To see if I can fix this problem.
Thank you~

**Comment by jdneo** [comment]
@yihong0618 Appreciated for your contribution, thanks!

**Comment by yihong0618** [comment]
> @yihong0618 Appreciated for your contribution, thanks!
@jdneo 
Can you test the GitHub and LinkedIn new payload way to login for leetcode? For leetcode-cn the api had changed so much, maybe need some time

**Comment by yihong0618** [comment]
> > @yihong0618 Appreciated for your contribution, thanks!
> > @jdneo
> > Can you test the GitHub and LinkedIn new payload way to login for leetcode? For leetcode-cn the api had changed so much, maybe need some time

Leetcode-cn login problem fixed.

**Comment by jdneo** [comment]
@zry656565 Could you take a look at this PR? I do not have the knowledge how leetcode auth with linkedin.

**Comment by zry656565** [comment]
@jdneo To be honest, I am not very sure about it too. 😂

**Comment by yihong0618** [comment]
@zry656565 I think its just use LinkedIn session to login, you can test the old one (which is down) and the new one for linking your leetcode.com account with LinkedIn. Thanks.

**Pull request merged**
