### PR TITLE
add leetcode user -c that user can login with cookie

### PR DESCRIPTION
**Pull request by yihong0618**
Add a method that user can login with cookie relate to [vscode-leetcode can't login problem](https://github.com/jdneo/vscode-leetcode/issues/478)

### CODE REVIEW

**Comment by yihong0618** [comment]
Sorry I did not get the point of travis-ci error

**Comment by jdneo** [comment]
Thank you @yihong0618. 

I'll take a look for this change recently. Probably on Sunday or next Monday.

**Comment by wanquanw** [comment]
It seems like that the travis-ci errors are about code style problems.

**Comment by jdneo** [comment]
Thanks @yihong0618,

Do you need me to publish it now? I have no Windows machine on my side for now, so I cannot check my the CI job fails.

It would be great if you can help verify it. 😄

**Comment by yihong0618** [comment]
Yes, please. And it seems that I can't find anything useful for the ci message. Sorry I did not find my error.
And I think in the vscode-leetcode side only need to add **leetcode.cookieIn**(maybe like leetcode.signIn just change password to cookie) is OK. But I think its a bad idea for solve the problem. LOL~

**Comment by jdneo** [comment]
@yihong0618 Hmm, can we open a webview to automatically get the cookie? The webview in VS Code could not achieve that because the VS Code team does not provide APIs to do that. I'm not sure if there is a easy-to-go solution in Node.js.

**Comment by jdneo** [comment]
2.6.17 released

**Comment by yihong0618** [comment]
@jdneo 
Seems hard but I can try ~. If the webview can load the whole login page will be nice.
I found this [article](https://medium.com/@jsoverson/bypassing-captchas-with-headless-chrome-93f294518337) may help, but to bypass the code not only need time and money, and the **Headless Chrome**  is about 100MB, kind of  not worth it

**Comment by jdneo** [comment]
Oh, that's a great article. thanks for sharing.

Yes I agree that if we need 100M more size to bypass it, there is no need to do that.

**Pull request merged**
